addded rollback and test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -161,6 +161,9 @@ jobs:
           kubectl apply -f dep-ser/secrets.yml
           kubectl apply -f dep-ser/backe.yml
           kubectl rollout restart deployment backend -n default
+      - name: Verify Backend Deployment & Rollback on Failure
+        run: |
+          kubectl rollout status deployment backend -n default || (echo "Backend deployment failed! Rolling back..." && kubectl rollout undo deployment backend -n default)
 
       - name: Wait for Backend Load Balancer IP
         run: |
